import { CampaignsTable } from "@/components/campanhas/campaigns-table";
import { Container } from "@/components/global/container";
import { Heading } from "@/components/global/heading";
import { Section } from "@/components/global/section";
import type { Campaign } from "@/types/campaigns";

export default function Campaigns() {

  const mockCampaigns: Campaign[] = [
    {
      id: "1",
      segment: "E-commerce",
      message: "Promoção de Black Friday - 50% de desconto em todos os produtos!",
      client: "Loja Virtual Ltda",
      multiplier: 2.5,
      validity: "30d",
      notificationCost: 0.15,
      status: "published",
      business: "Varejo Online",
      cnpj: "12.345.678/0001-90",
      totalValue: 15000.00,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-20"),
    },
    {
      id: "2",
      segment: "Saúde",
      message: "Agende sua consulta médica com 20% de desconto",
      client: "Clínica Saúde Total",
      multiplier: 1.8,
      validity: "15d",
      notificationCost: 0.20,
      status: "hired",
      business: "Serviços Médicos",
      cnpj: "98.765.432/0001-10",
      totalValue: 8500.00,
      createdAt: new Date("2024-01-05"),
      updatedAt: new Date("2024-01-18"),
    },
    {
      id: "3",
      segment: "Educação",
      message: "Matrículas abertas para cursos de programação",
      client: "Escola de Tecnologia",
      multiplier: 3.0,
      validity: "10d",
      notificationCost: 0.12,
      status: "rejected",
      business: "Educação",
      cnpj: "45.678.901/0001-23",
      totalValue: 22000.00,
      createdAt: new Date("2024-01-06"),
      updatedAt: new Date("2024-01-12"),
    },
    {
      id: "4",
      segment: "Alimentação",
      message: "Delivery gratuito em pedidos acima de R$ 30",
      client: "Restaurante Sabor Caseiro",
      multiplier: 2.2,
      validity: "5d",
      notificationCost: 0.18,
      status: "published",
      business: "Gastronomia",
      cnpj: "67.890.123/0001-45",
      totalValue: 12000.00,
      createdAt: new Date("2024-01-11"),
      updatedAt: new Date("2024-01-16"),
    },
    {
      id: "5",
      segment: "Automotivo",
      message: "Revisão completa com 30% de desconto",
      client: "Auto Center Premium",
      multiplier: 1.5,
      validity: "20d",
      notificationCost: 0.25,
      status: "hired",
      business: "Serviços Automotivos",
      cnpj: "34.567.890/0001-67",
      totalValue: 9500.00,
      createdAt: new Date("2024-01-08"),
      updatedAt: new Date("2024-01-19"),
    },
    {
      id: "6",
      segment: "Beleza",
      message: "Pacote de tratamentos faciais com 40% OFF",
      client: "Spa Beleza Natural",
      multiplier: 2.8,
      validity: "45d",
      notificationCost: 0.16,
      status: "published",
      business: "Estética",
      cnpj: "78.901.234/0001-89",
      totalValue: 18000.00,
      createdAt: new Date("2024-01-03"),
      updatedAt: new Date("2024-01-14"),
    },
    {
      id: "7",
      segment: "Fitness",
      message: "Aulas de yoga online - 7 dias grátis",
      client: "Academia Fit Life",
      multiplier: 2.0,
      validity: "7d",
      notificationCost: 0.14,
      status: "hired",
      business: "Esportes",
      cnpj: "23.456.789/0001-12",
      totalValue: 7500.00,
      createdAt: new Date("2024-01-09"),
      updatedAt: new Date("2024-01-17"),
    },
    {
      id: "8",
      segment: "Tecnologia",
      message: "Assinatura anual com 25% de desconto",
      client: "Tech Solutions",
      multiplier: 3.5,
      validity: "60d",
      notificationCost: 0.22,
      status: "published",
      business: "Software",
      cnpj: "56.789.012/0001-34",
      totalValue: 28000.00,
      createdAt: new Date("2024-01-02"),
      updatedAt: new Date("2024-01-15"),
    },
    {
      id: "9",
      segment: "Viagem",
      message: "Pacotes de viagem para o Nordeste com 35% OFF",
      client: "Agência Viajar Mais",
      multiplier: 2.3,
      validity: "3d",
      notificationCost: 0.19,
      status: "rejected",
      business: "Turismo",
      cnpj: "89.012.345/0001-56",
      totalValue: 16000.00,
      createdAt: new Date("2024-01-13"),
      updatedAt: new Date("2024-01-13"),
    },
    {
      id: "10",
      segment: "Imobiliário",
      message: "Financiamento imobiliário com juros reduzidos",
      client: "Imobiliária Casa Certa",
      multiplier: 1.9,
      validity: "90d",
      notificationCost: 0.28,
      status: "hired",
      business: "Construção Civil",
      cnpj: "12.345.678/0001-78",
      totalValue: 11000.00,
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-18"),
    },
  ]
  
  return (
    <Section>
      <Container fullWidth>
        <Heading>Campanhas</Heading>
        <CampaignsTable campaigns={mockCampaigns} />
      </Container>
    </Section>
  )
}
